### ISSUE TITLE
Are tags required to have trailing whitespace?

### ISSUE THREAD

**Issue by richard-lyman** [edn-format/edn#14]
Is #prefix/name42 valid edn? Does it become the tag #prefix/name applied to the element 42?

**Comment by shaunxcode** [comment]
In your example - no because "prefix/name42" is a valid symbol. However if it is a form such as #someTag(1 2 3) that would apply someTag to list (1 2 3).

**Comment by richard-lyman** [comment]
Good point. If the entire file/stream of edn were #prefix/name42, then it wouldn't be valid - right? Also, #prefix/name:Keyword could not be taken to be a tagged element, it would just be a tag... right?

**Comment by shaunxcode** [comment]
Yes, #prefix/name:Keyword would be a valid tag as : is allowed within a symbol. 

": # are allowed as constituent characters in symbols but not as the first character. "

**Comment by richhickey** [comment]
tags terminate when the symbol does
