### ISSUE TITLE
Are \newline and \return considered the same?

### ISSUE THREAD

**Issue by richard-lyman** [edn-format/edn#15]
Two specific areas: Single-line comments and Characters.

**Comment by bpsm** [comment]
In Clojure \newline is line feed (ASCII 10) while \return is carriage return (ASCII 13).

**Comment by richard-lyman** [comment]
True. They are different characters. I'm wondering if the un-mentioned \return is intentional or if it's assumed that wherever \newline is referred to \return is also valid.
