### ISSUE TITLE
Is "#_ #_ 1 2 3" equivalent to "#_ 1 #_ 2 3"?

### ISSUE THREAD

**Issue by bpsm** [edn-format/edn#19]
It's not clear to me if  "#_ #_ 1 2 3" is equivalent to "#_ 1 #_ 2 3". This is the case in Clojure's LispReader, but I thought I'd ask to be certain.

(One could argue for "#_ #_ 1 2 3" being equivalent to "1 2 3" if the first #_ were to eat the second.)

**Comment by richard-lyman** [comment]
From the way I feel the current casual spec is worded, the string "#_ #_ 1 2 3" would not be valid edn. I don't see any mention of the sequence "#_" being an Element in edn, but upon reading the first "#_" the restriction, "...the next element must still be a readable element" would kick in, and you'd be reading "#_" - which isn't an Element.

If "#_" were an Element, then I'd take the current descriptions literally and say that "#_ #_ 1 2 3" => "1 2 3" which doesn't feel as _right_ as becoming "3" (to me it feels OK to 'nest' the 'comment' sequence '#_").

**Comment by bpsm** [comment]
butterfingers.

**Comment by richhickey** [comment]
#_ is not an element - it is a directive that says 'discard the next element'. So in #_ #_ 1 2 3, the first #_ tries to read an element, so does the second, which discards 1, then the first #_ gets and discards 2, IOW it groups like this:

(#_ (#_ 1) 2) 3
