### ISSUE TITLE
is "foo/-0bar" an acceptable symbol?

### ISSUE THREAD

**Issue by bpsm** [edn-format/edn#23]
"If - or . are the first character, the second character must be non-numeric. Additionally, : # are allowed as constituent characters in symbols but not as the first character."

So, is "foo/-4bar" allowed or not? It would seem allowed, but this has the unfortunate property that the we're left with an unreadable symbol if we strip the prefix: "-4bar".

**Comment by richard-lyman** [comment]
It would seem to make sense to me to do as you might be suggesting.

Maybe Symbol Prefix and Name are each required to fulfill all the rules for Symbols... so... a Symbol is either a pair of Symbols joined with a \/, or a Single Symbol that can not have \/.
