### ISSUE TITLE
".4bar" is not an acceptable symbol, though it is unambiguous since numbers can't start with "."

### ISSUE THREAD

**Issue by bpsm** [edn-format/edn#24]
I follow forbidding "-4bar" since that means potentially unbounded look-ahead to distinguish numbers from non-numbers.

Presumably forbidding ".4bar" is for the same reason, though ".1" doesn't appear to be a valid numeric literal. (Numeric literals all start with a digit.)

**Comment by richhickey** [comment]
leaving open the possibility of .1 becoming a valid number
