### ISSUE TITLE
What to do with Double/POSITIVE_INFINITY and Double/NEGATIVE_INFINITY?

### ISSUE THREAD

**Issue by cndreisbach** [edn-format/edn#25]
When reading in certain numbers ("0.309222940550554E56687886556350", for example), I end up with Infinity in my target language (Ruby). Should I output these as Double/POSITIVE_INFINITY or Double/NEGATIVE_INFINITY, or are numbers of this size unsupported?

**Comment by richhickey** [comment]
You shouldn't get numbers bigger than 64-bit without the M suffix, but this would be ok:

3.09222940550554E+56686M

In that case, is there a BigDecimal class for Ruby?

**Comment by cndreisbach** [comment]
There is a BigDecimal class, which I can use. Good idea.
