### ISSUE TITLE
Are Sets also considered delimiters for not needing whitespace?

### ISSUE THREAD

**Issue by richard-lyman** [edn-format/edn#28]
Specifically, are the delimiters for a Set in the group that, "need not be separated from adjacent elements by whitespace?"

The delimiters () {} and [] are already mentioned... should #{ be added as not needing leading whitespace?

**Comment by richhickey** [comment]
No. foo#{...} is the symbol foo# followed by a map. # is not a delimiter

**Comment by richard-lyman** [comment]
If I understand correctly then, To identify a set you'd be required to prefix it with whitespace and the symbol } already does not require trailing whitepsace, so foo#{1}2 is the symbol foo# followed by a map containing the Integer 1 followed by the Integer 2 and 'foo #{1}2' is the symbol foo followed by a set containing the Integer 1 followed by the Integer 2 - right?

That makes more sense.
