### ISSUE TITLE
Is `:/` a valid keyword?

### ISSUE THREAD

**Issue by DerGuteMoritz** [edn-format/edn#32]
The spec says about symbols that "`/` by itself is a legal symbol" and continues that "[k]eywords follow the rules of symbols, except they can (and must) begin with a colon, e.g. `:fred` or `:my/fred`". So `:/` seems to be a valid keyword. Is this intended?

**Comment by richard-lyman** [comment]
If this is a continuation of my previous issue (https://github.com/edn-format/edn/issues/17), then I have related comments at that previous issue.

**Comment by DerGuteMoritz** [comment]
It's similar but not the same which is why I decided to open a new ticket. Yours is about how the semantics of "beginning of symbol" map to keywords while mine is about how the special cased `/` symbol maps to keywords.

**Comment by richard-lyman** [comment]
True, true. They are different in the exact point they're making.

**Comment by richhickey** [comment]
neither :/ nor :/foo are valid. I'll cover these in the next edit.
