### ISSUE TITLE
Link to Implementations page in the Readme

### ISSUE THREAD

**Issue by gnarmis** [edn-format/edn#34]
It'd be nice to have it right there when newcomers see the Readme.

https://github.com/edn-format/edn/wiki/Implementations

**Comment by richard-lyman** [comment]
Part of me agrees and part of me doesn't.

The spec isn't final. Once it's final I kinda think it should have some test data that allows an implementation to state how much of Edn it can handle. Once we can talk about conformance as a metric, then I think it makes sense to publicize fully conforming implementations. This brings up another issue I keep forgetting to file... anyway, my point is - I don't think it'd help to have someone get the wrong idea about what Edn is by using an incomplete implementation--or even just an implementation that is based on an old description of an unfinished spec.

**Comment by gnarmis** [comment]
Hmm, as long as it's prefaced like that it might be fine. It's not a big deal though, it's still accessible in Wiki.

**Comment by richhickey** [comment]
Let's leave it to wiki for now.
