### ISSUE TITLE
iOS framework?

### ISSUE THREAD

**Issue by luposlip** [edn-format/edn#37]
Hi Rich,

Have you heard of any iOS frameworks for parsing/generating EDN?
If not, I might do one for myself (and open sourcing it afterwards).

Best,
Henrik

**Comment by richhickey** [comment]
I haven't - go for it!

**Comment by luposlip** [comment]
Deal!

**Comment by scramjet** [comment]
Hello Rich and Henrik. FYI I've just posted an open source EDN reader/writer I developed for iOS and OS X at https://github.com/scramjet/mpedn.

**Comment by luposlip** [comment]
Excellent Mathew, to be honest my own work in this area hasn't progressed much since my first post, so I'll consider using your implementation and join forces instead of keeping rolling my own :-)

BRgds,
Henrik

Den 24/02/2013 kl. 01.14 skrev Matthew notifications@github.com:
