### ISSUE TITLE
Can literal tags contain periods?

### ISSUE THREAD

**Issue by lynaghk** [edn-format/edn#39]
The Clojure reader currently does not allow periods in tagged literals (see http://dev.clojure.org/jira/browse/CLJ-1100). The EDN spec is unclear on this issue:

> edn supports extensibility through a simple mechanism. # followed immediately by a symbol starting with an alphabetic character indicates that that symbol is a tag.

Are periods allowed in tags?

**Comment by richhickey** [comment]
edn spec is not unclear, I think. Periods are allowed, as they are in symbols. The prefix/namespace requirement stands for user tags though. The Clojure reader check is naive, and should first look for namespace. w/o namespace is reserved, and Clojure takes that for built-ins and records.

**Comment by lynaghk** [comment]
Ah, that was my feeling. Thanks Rich.
