### ISSUE TITLE
Ordered Map?

### ISSUE THREAD

**Issue by nahuel** [edn-format/edn#4]
What about an ordered map syntax? Many XML applications use the implicit definition order, maybe using ordered maps is better than using lists for some tasks.

**Comment by jrus** [comment]
Can’t you just use an extension for that? `#nahuel/omap [key1 val1, key2 val2, key3 val3]` or whatever?

**Comment by nahuel** [comment]
Sure, but is a common case, so maybe it deserves his own native syntax.

**Comment by richhickey** [comment]
I don't think it does. You are treading into document territory there, and documents are well served by *ml.
