### ISSUE TITLE
EDN Schemas?

### ISSUE THREAD

**Issue by brandonbloom** [edn-format/edn#40]
Considering EDN is a simpler XML, can we also get a simpler XSD?

David Nolen and I were discussing the potential for formalizing the ClojureScript AST. My first thought was that I wish I had an AST validator, like the ASTValidator.java in Google Closure. My next thought was "I'm sure core.logic could make this very easy". I typed not more than two sentences of notes on this topic before I thought: This smells an awful lot like XML Schemas...

**Comment by trevor** [comment]
:+1:

**Comment by Chouser** [comment]
Would Prismatic's schema suffice?
https://github.com/prismatic/schema

**Comment by trevor** [comment]
@Chouser thanks!

**Comment by brandonbloom** [comment]
@Chouser Funny timing. David just brought this topic back up today in IRC.

Prismatic's schema probably covers this for many folks, but it's probably not the right fit for the ClojureScript compiler's needs for a variety of reasons not worth going in to here.

**Comment by trevor** [comment]
@brandonbloom Off-topic: I use fipp every day. :heart: :beers:

**Comment by brandonbloom** [comment]
@trevor Awesome! I get so few bug reports that I can only assume A) Nobody uses it or B) It's perfect. From now on, I'll assume #2.

**Comment by richhickey** [comment]
Schemas out of scope for now.

**Comment by brandonbloom** [comment]
Now that we've got a simpler XML _and_ a simpler XSD, can we get a simpler XPath? ;) Thanks much for the work on this and clojure.spec!

**Comment by rschmitt** [comment]
@brandonbloom Pardon my ignorance, but what is the simpler XSD you're referring to?

**Comment by brandonbloom** [comment]
https://clojure.org/about/spec

**Comment by rschmitt** [comment]
I guess you can call spec a simpler XSD; I think I was just taking you too literally.
