### ISSUE TITLE
Would #<...> be valid edn?

### ISSUE THREAD

**Issue by trevorbernard** [edn-format/edn#41]
Greater than and less than aren't in the symbols section and I would like some clarification. Can you have greater than and less than in tags in edn?

**Comment by bjeanes** [comment]
My guess would be that, no it would not be valid. Both `<` and `>` are valid symbols in of themselves (e.g. in Clojure, `(< 2 3) ;=> true` so they probably could not be used unambiguously as delimiters a la `(`, `)`, `{`, `}`

**Comment by richhickey** [comment]
Nothing in the spec implies that it would afaict.
