### ISSUE TITLE
EdnReader.java is more liberal with numbers than defined here. Which is correct?

### ISSUE THREAD

**Issue by bjeanes** [edn-format/edn#47]
The regex at https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/EdnReader.java#L28-L30 allows for octal, hex, and arbitrary base (e.g. 3r2011012) ints.

Is the edn definition incomplete or is the clojure EDN reader too liberal?

**Comment by bpsm** [comment]
[EdnReader.java](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/EdnReader.java#L360) also accepts rationals without complaint, but those go unmentioned in the spec. It looks to me like an accident resulting from the fact that EdnReader.java began as a copy-paste job of [LispReader.java](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/EdnReader.java).

There's a meta-point here: I don't think it's helpful if every edn reader supports a _different_ **superset** of the notation described by the spec.

See also bpsm/edn-java#34.

**Comment by richhickey** [comment]
EDN read is more liberal than the spec. I don't see that as a problem, as the spec is the arbiter, not implementations. The spec is going to start conservatively, but these may be added iff there is demand/need.
