### ISSUE TITLE
Escape characters in strings

### ISSUE THREAD

**Issue by mperrotta** [edn-format/edn#49]
Am I correct to assume that only the 3 escape sequences \t \r \n are supported in EDN strings? Seems to not be complete since escaped double quotes are so common?

**Comment by sheerun** [comment]
Exactly.This list should be extended with at least `\"`, `\\`.

And what about `\f`, `\b`, `\u123` like in JSON?

@richhickey This issue has 8 months and is easy to fix. Could you spare some time, review all issues on this repository, and apply appropriate changes? I think lack of maintenance has negative impact on popularity and seriousness of EDN..

**Comment by sheerun** [comment]
Awesome!
