### ISSUE TITLE
Does edn consider `foo//` to be a valid symbol?

### ISSUE THREAD

**Issue by bpsm** [edn-format/edn#51]
This is a follow-up to the recent commit clojure/clojure@88cad2510243289d2bbe28cf8bd14007d9df5fc3.

Currently, [bpsm/edn-java](https://github.com/bpsm/edn-java/) rejects the symbol `foo//`. I suspect now that [this is not correct](https://github.com/bpsm/edn-java/blob/master/src/main/java/us/bpsm/edn/parser/ScannerImpl.java#L498) behavior.

```
commit 88cad2510243289d2bbe28cf8bd14007d9df5fc3
Author: Chris Gray <chrismgray@gmail.com>
Date:   2011-11-09 22:23:15 -0700

    Allow foo// meaning the function / in namespace foo

    Added regression tests

    Signed-off-by: Stuart Halloway <stu@thinkrelevance.com>
```

**Comment by richhickey** [comment]
Does the spec imply it doesn't?

**Comment by wagjo** [comment]
I would say that specs permits `/` to be used either alone or **once only in the middle** of the symbol. I don't see where the specs allows for `/` to be part of the _name_. Current specs reads

>  / has special meaning in symbols. It can be used once only in the middle of a symbol to separate the prefix (often a namespace) from the name, e.g. my-namespace/foo. / by itself is a legal symbol, but otherwise neither the prefix nor the name part can be empty when the symbol contains /.
