### ISSUE TITLE
support for metadata? 

### ISSUE THREAD

**Issue by shaunxcode** [edn-format/edn#52]
I noticed that the relevance/edn-ruby lib is supporting metadata e.g. 
`^{:doc "This is my vector" :rel :temps} [98.6 99.7]`

Is this going to be part of the official edn spec? At the very least I can imagine suggesting that languages which do not have support for metadata can treat it as a comment/discard?

**Comment by benmosher** [comment]
I added support for it in my `obj-c` implementation, but I can see the argument that metadata should not leave memory, though; its presence/lack thereof does not impact the 'value' of an entity (equality, etc.), and isn't that what you're serializing, ultimately?

That said, I suspect consumers/producers to want to be able to write it out to disk, over networks, etc... (so, +1)

**Comment by richhickey** [comment]
Yes, it is hoped that edn will support metadata. As you mention, there needs to be a plan for consumers in langs that don't directly support it.
