### ISSUE TITLE
support for formfeed character

### ISSUE THREAD

**Issue by shaunxcode** [edn-format/edn#55]
It appears that \formfeed (\f) is also a valid character along with \newline \return etc. If this is the case the spec should be updated to reflect it? (I am basing its validity on the basis that clojure.edn/read-string accepts it).

**Comment by richhickey** [comment]
It's not allowed. At some point edn/read-string should disallow, but edn/read-string's purpose is not to validate incorrect edn, but rather to read correct edn.
