### ISSUE TITLE
Unicode and Symbols

### ISSUE THREAD

**Issue by richard-lyman** [edn-format/edn#6]
In the explanation for Symbols it says, "non-numeric character" and "alphanumeric characters." Are those restricted to ASCII or can relevant Unicode fit?

[The wikipedia page for 'alphanumeric'](http://en.wikipedia.org/wiki/Alphanumeric) states that it is commonly restricted to Latin Letters and Arabic Digits, but then makes exception for 'other locales.'

**Comment by mikera** [comment]
FWIW, I think it make sense to restrict to ASCII - this is going to make it much simpler for implementers / parser writers! Unicode is already supported in Strings if people need it.

**Comment by tomia** [comment]
As the expected encoding is utf-8 would expect the definition of http://www.unicode.org/reports/tr18/ (alnum - property) to hold.

**Comment by richhickey** [comment]
I don't see why not.
