### ISSUE TITLE
The edn spec inaccurately describes what characters are allowed in symbols.

### ISSUE THREAD

**Issue by bitemyapp** [edn-format/edn#62]
Just show the damn symbolPat regex from Clojure core.

The spec even forgets < is a valid symbol despite using it in the Datomic tutorial.

**Comment by alexanderkiel** [comment]
You are right `(type (clojure.edn/read-string "<"))` returns `clojure.lang.Symbol` in clojure 1.5.1.

**Comment by alexanderkiel** [comment]
To clarify this further, the spec says in [section symbols](https://github.com/edn-format/edn#symbols):

> Symbols begin with a non-numeric character

This includes `<`.

**Comment by bitemyapp** [comment]
:+1:
