### ISSUE TITLE
json-ld, #iri

### ISSUE THREAD

**Issue by mobileink** [edn-format/edn#63]
I'm looking at using EDN for some RDF data (like json-ld), so I'll have to define a tagged element for IRIs, e.g. #foo/iri.  A builtin tagged element for IRIs (RFC 3987) would be helpful.

Thanks,

gregg

**Comment by richhickey** [comment]
While interesting, it could be dangerous to include a standard tag that requires more effort to support than edn itself. I guess it depends on the implied semantics, required validation or lack thereof.
