### ISSUE TITLE
Can Keywords contain escape characters?

### ISSUE THREAD

**Issue by arnm** [edn-format/edn#69]
Would keywords like `:\n`, `:\r`, etc. be valid? I assume not because Clojure does not allow them but I didn't see it in the Spec so I might be wrong.

**Comment by xpe** [comment]
Correct; those examples are not valid.

The Spec clears this up. See these parts:

> Keywords are identifiers that typically designate themselves. They are semantically akin to enumeration values. **Keywords follow the rules of symbols**, except they can (and must) begin with :, e.g. :fred or :my/fred.
> 
> **Symbols begin with a non-numeric character and can contain alphanumeric characters and `. * + ! - _ ? $ % & = < >`.** If `-`, `+` or `.` are the first character, the second character (if any) must be non-numeric. Additionally, : # are allowed as constituent characters in symbols other than as the first character.

The backslash is not an allowed character in a symbol nor a keyword.

I think we can close this issue now.
