### ISSUE TITLE
Clarifying the definition of 'constituent characters' in Symbols

### ISSUE THREAD

**Issue by richard-lyman** [edn-format/edn#7]
I found [the clisp page on constituent](http://clhs.lisp.se/Body/26_glo_c.htm#constituent), and that seems to mean that the related character is valid for that element in edn. Is that correct?

I'm confused about where : and # are valid in Symbols. Clearly they can be 'in' a Symbol, and not the first character. [The Clojure Reader page](http://clojure.org/reader) says that Symbols ending with : are reserved by Clojure - is that also true of edn? That same Clojure Reader page says that : must be non-repeating. Is that true in edn of : and #?

**Comment by richhickey** [comment]
The edn spec exists in part to avoid people consuming edn from having to understand the _interpretation_ of edn by Clojure compiler. Something can be a valid symbol that is further reserved in Clojure. It's best to understand edn in terms of its own spec and avoid the Clojure reader page.
