### ISSUE TITLE
Tagged Elements Issue?

### ISSUE THREAD

**Issue by g3ntleman** [edn-format/edn#72]
The result from evaluating `(ns-refers *ns*)` contains thinks like

`#'clojure.core/+`

for which I'm uncertain what is meant from the spec. It starts like a tagged value, but those require an alphabetic character following, which is not the case here (`'`).
So should be whole thing be parsed as the symbol `+` with a namespace of `#'clojure.core`?

Does not seem right to me. Could someone please clarify?

**Comment by g3ntleman** [comment]
Ok, I found that this is the Var-Quote Macro. 

Var-quote (#')
#'x ⇒ (var x)

So is #'clojure.core valid EDN? at all?

**Comment by rschmitt** [comment]
No, nor is it supposed to be, since Clojure programs are written in a superset of Edn. `#'` is a Clojure reader macro and `var` is a special form.

**Comment by g3ntleman** [comment]
Thanks!
